In [1]:
from IPython.core.interactiveshell import InteractiveShell  #使所有结果都输出
InteractiveShell.ast_node_interactivity = "all"
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import metrics
from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_curve, auc  ###计算roc和auc
from sklearn import model_selection
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import AdaBoostClassifier
from sklearn.datasets import make_blobs
import matplotlib as plt
from sklearn.tree import DecisionTreeClassifier

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
import matplotlib.pyplot as plt
from sklearn.preprocessing import minmax_scale
from sklearn.metrics import precision_score, roc_curve, recall_score, f1_score, roc_auc_score, accuracy_score
import warnings

import os
import pandas as pd
import numpy as np
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from pandas import DataFrame
import xgboost as xgb

In [2]:
df = pd.read_csv('train连续.csv')
print(df.shape)
df.head()

(1974, 23)


id                                             SMILES  pIC50   MDEC-23  nC  \
0   1  Oc1ccc2O[C@H]([C@H](Sc2c1)C3CCCC3)c4ccc(OCCN5C...  8.602  28.27793  26   
1   2  Oc1ccc2O[C@H]([C@H](Sc2c1)C3CCCCCC3)c4ccc(OCCN...  8.125  31.07675  28   
2   3  Oc1ccc(cc1)[C@H]2Sc3cc(O)ccc3O[C@H]2c4ccc(OCCN...  8.509  30.90106  27   
3   4  Oc1ccc2O[C@H]([C@@H](CC3CCCCC3)Sc2c1)c4ccc(OCC...  8.409  30.57000  28   
4   5  Oc1ccc2O[C@H]([C@@H](Cc3ccccc3)Sc2c1)c4ccc(OCC...  8.131  30.57000  28   

   C1SP2   minHsOH     minsOH  nHBAcc    maxssO  ...   MDEO-12   minsssN  \
0      0  0.469126   9.968948       1  6.593009  ...  0.269680  2.516142   
1      0  0.449126  10.058950       1  6.674642  ...  0.269680  2.521244   
2      0  0.480713   9.752886       1  6.502751  ...  0.495846  2.484448   
3      0  0.456486  10.025030       1  6.622142  ...  0.269680  2.519774   
4      0  0.473631   9.993342       1  6.552810  ...  0.269680  2.504217   

   MLFER_A    MDEC-33      VC-5  ETA_Shape_Y  minHBint10     SHsOH  SHBint10  \
0    0.546   9.238227  0.230311      0.28884    0.000000  0.469126  0.000000   
1    0.546   9.238227  0.230311      0.27105    0.000000  0.449126  0.000000   
2    1.089  10.328980  0.174055      0.30498    4.688339  0.997247  9.842059   
3    0.546   8.529910  0.123273      0.27105    0.000000  0.456486  0.000000   
4    0.546   8.529910  0.123273      0.27105    0.000000  0.473631  0.000000   

    ALogP  
0 -0.2860  
1 -0.8620  
2  0.7296  
3 -0.3184  
4  1.3551  

[5 rows x 23 columns]

In [3]:
# 准备数据
target = ['id','SMILES','pIC50']
X = df.drop(target, axis=1)
y = df['pIC50']
print(X.shape, y.shape)

(1974, 20) (1974,)


In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)
from xgboost import XGBRegressor
my_model = XGBRegressor(n_estimators=1000, learning_rate=0.05)
my_model.fit(X_train, y_train, early_stopping_rounds=5, 
             eval_set=[(X_test, y_test)], verbose=False)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.05, max_delta_step=0, max_depth=6,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=1000, n_jobs=8, num_parallel_tree=1, random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [6]:
#训练集 y的预测值
fit_pred=my_model.predict(X_test)
fit_pred

array([8.931367 , 6.105515 , 8.971199 , 5.2808   , 4.849008 , 5.267157 ,
       5.3659983, 8.281023 , 5.0120683, 4.928538 , 5.209001 , 6.4195437,
       7.573254 , 5.1563153, 5.6103168, 8.760298 , 6.5848327, 4.750073 ,
       4.954782 , 8.637019 , 5.191366 , 5.279832 , 7.758912 , 6.9345837,
       8.17898  , 6.9892855, 5.8461285, 4.614165 , 6.4970055, 5.927152 ,
       5.052112 , 7.557833 , 5.574234 , 7.0248175, 4.623758 , 5.7870703,
       7.9175134, 7.989196 , 6.943515 , 4.812575 , 6.6307516, 7.1837945,
       5.0778875, 7.139897 , 4.829145 , 5.3697433, 6.03851  , 7.9056644,
       6.9074874, 7.844675 , 7.350724 , 7.0478745, 8.128286 , 4.179091 ,
       5.866832 , 5.114608 , 7.1289234, 6.056616 , 5.8531675, 6.0747004,
       7.6822   , 7.0377617, 8.354563 , 8.458995 , 4.6550865, 5.2808   ,
       6.592723 , 6.9989324, 7.4727435, 7.8007264, 5.8258595, 6.730037 ,
       6.603881 , 6.892542 , 8.920819 , 4.749246 , 4.719719 , 9.032197 ,
       5.5143437, 6.4678693, 5.216911 , 7.5843596, 

In [7]:
data11=pd.DataFrame(y_test)
data11   #y的真实值

pIC50
273   9.097
433   6.428
277   9.523
1002  4.921
1187  5.165
...     ...
733   4.153
257   8.824
953   6.357
1910  9.523
1816  7.276

[395 rows x 1 columns]

In [9]:
#根据题目中给定的训练集，进行预测
aa=pd.read_csv('test连续.csv')
pred=my_model.predict(aa)
pred
data2=pd.DataFrame(pred)  #y的预测数据
data2

array([7.4984775, 7.2952337, 7.2736826, 7.5399675, 7.425395 , 7.881566 ,
       7.4187317, 7.3579736, 6.846984 , 7.406498 , 7.289636 , 7.4223194,
       7.446312 , 7.3007913, 7.364187 , 7.3490257, 7.539592 , 6.608518 ,
       6.885767 , 7.568061 , 6.534535 , 6.7123947, 5.7896333, 5.923038 ,
       5.3803244, 5.5398145, 7.112732 , 5.833447 , 5.7916036, 5.7757497,
       4.897998 , 4.8921046, 4.9479423, 4.735308 , 4.6106677, 5.3243513,
       5.393025 , 6.35285  , 6.5023265, 6.518695 , 6.518695 , 6.518695 ,
       6.5023265, 6.460377 , 6.518695 , 6.9078298, 6.9228067, 6.728187 ,
       6.1670494, 6.472499 ], dtype=float32)

0
0   7.498477
1   7.295234
2   7.273683
3   7.539968
4   7.425395
5   7.881566
6   7.418732
7   7.357974
8   6.846984
9   7.406498
10  7.289636
11  7.422319
12  7.446312
13  7.300791
14  7.364187
15  7.349026
16  7.539592
17  6.608518
18  6.885767
19  7.568061
20  6.534535
21  6.712395
22  5.789633
23  5.923038
24  5.380324
25  5.539814
26  7.112732
27  5.833447
28  5.791604
29  5.775750
30  4.897998
31  4.892105
32  4.947942
33  4.735308
34  4.610668
35  5.324351
36  5.393025
37  6.352850
38  6.502326
39  6.518695
40  6.518695
41  6.518695
42  6.502326
43  6.460377
44  6.518695
45  6.907830
46  6.922807
47  6.728187
48  6.167049
49  6.472499

In [12]:
my_model.score(X_test,y_test)

0.7475011231319997

回归模型的四大评价指标

explained_variance_score：解释回归模型的方差得分，其值取值范围是[0,1]，越接近于1说明自变量越能解释因变量
    的方差变化，值越小则说明效果越差。
    mean_absolute_error：平均绝对误差（Mean Absolute Error，MAE），用于评估预测结果和真实数据集的接近程度的程度
    ，其其值越小说明拟合效果越好。
    mean_squared_error：均方差（Mean squared error，MSE），该指标计算的是拟合数据和原始数据对应样本点的误差的
    平方和的均值，其值越小说明拟合效果越好。
    r2_score：判定系数，其含义是也是解释回归模型的方差得分，其值取值范围是[0,1]，越接近于1说明自变量越能解释因
    变量的方差变化，值越小则说明效果越差。

In [22]:
#回归模型的四大评价指标
#1、解释回归模型的方差得分，其值取值范围是[0,1]，越接近于1说明自变量越能解释因变量 的方差变化，值越小则说明效果越差
from sklearn.metrics import explained_variance_score
explained_variance_score(y_test,fit_pred)
#2、平均绝对误差（Mean Absolute Error，MAE），用于评估预测结果和真实数据集的接近程度的程度 ，其其值越小说明拟合效果越好

#3、均方差（Mean squared error，MSE），该指标计算的是拟合数据和原始数据对应样本点的误差的 平方和的均值，其值越小说明拟合效果越好

#4、判定系数，其含义是也是解释回归模型的方差得分，其值取值范围是[0,1]，越接近于1说明自变量越能解释因 变量的方差变化，值越小则说明效果越差



0.7477426378886016

In [ ]:
from __future__ import division
from sklearn.metrics import explained_variance_score, mean_absolute_error, mean_squared_error, r2_score
def calPerformance(y_true,y_pred):
    model_metrics_name=[explained_variance_score, mean_absolute_error, mean_squared_error, r2_score]  
    tmp_list=[]  
    for one in model_metrics_name:  
        tmp_score=one(y_true,y_pred)  
        tmp_list.append(tmp_score)  
    print ['explained_variance_score','mean_absolute_error','mean_squared_error','r2_score']
    print tmp_list
    return tmp_list
 
calPerformance(y_true,y_pred)

In [23]:
#根据题目中给定的训练集，进行预测
aa=pd.read_csv('test连续.csv')
pred=my_model.predict(aa)
pred

data2=pd.DataFrame(pred)  #y的预测数据
data2
data2.to_csv("连续变量的预测结果.csv")

array([7.4984775, 7.2952337, 7.2736826, 7.5399675, 7.425395 , 7.881566 ,
       7.4187317, 7.3579736, 6.846984 , 7.406498 , 7.289636 , 7.4223194,
       7.446312 , 7.3007913, 7.364187 , 7.3490257, 7.539592 , 6.608518 ,
       6.885767 , 7.568061 , 6.534535 , 6.7123947, 5.7896333, 5.923038 ,
       5.3803244, 5.5398145, 7.112732 , 5.833447 , 5.7916036, 5.7757497,
       4.897998 , 4.8921046, 4.9479423, 4.735308 , 4.6106677, 5.3243513,
       5.393025 , 6.35285  , 6.5023265, 6.518695 , 6.518695 , 6.518695 ,
       6.5023265, 6.460377 , 6.518695 , 6.9078298, 6.9228067, 6.728187 ,
       6.1670494, 6.472499 ], dtype=float32)

交叉验证代码

In [ ]:
data1= pd.read_csv('D:\ssjm\data1.csv',encoding='gbk')
data= pd.read_csv('D:\ssjm\data.csv',encoding='gbk')
from sklearn import linear_model
from sklearn import tree
model2_tree = tree.DecisionTreeRegressor()
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import cross_val_score
target=data['pIC50']#target为因变量，data1为只有自变量的数据
model1_linear = linear_model.LinearRegression()
from sklearn import svm
model3_SVR = svm.SVR()
from sklearn.neighbors import KNeighborsRegressor
model4_KN = KNeighborsRegressor(n_neighbors=3)
from sklearn.ensemble import RandomForestRegressor
model5_RF = RandomForestRegressor()
from sklearn.ensemble import AdaBoostRegressor
model6_AdaBoost = AdaBoostRegressor(n_estimators=100)
from sklearn.ensemble import GradientBoostingRegressor
model7_GBDT = GradientBoostingRegressor()
from sklearn.ensemble import BaggingRegressor
model8_Bagging = BaggingRegressor()
from sklearn.tree import ExtraTreeRegressor
model9_Etra = ExtraTreeRegressor()
#mse1=cross_val_score(model1_linear, data1, target,scoring="neg_mean_squared_error", cv=5).mean()
#mse2=cross_val_score(model2_tree, data1, target,scoring="neg_mean_squared_error", cv=5).mean()
#mse3=cross_val_score(model3_SVR, data1, target,scoring="neg_mean_squared_error", cv=5).mean()
#mse4=cross_val_score(model4_KN , data1, target,scoring="neg_mean_squared_error", cv=5).mean()
mse5=cross_val_score(model5_RF, data1, target,scoring="neg_mean_squared_error", cv=5).mean()
mse6=cross_val_score(model6_AdaBoost,target,scoring="neg_mean_squared_error", cv=5).mean()
mse7=cross_val_score(model7_GBDT, target,scoring="neg_mean_squared_error", cv=5).mean()
mse8=cross_val_score(model8_Bagging, target,scoring="neg_mean_squared_error", cv=5).mean()
mse9=cross_val_score(model9_Etra, target,scoring="neg_mean_squared_error", cv=5).mean()
#绝对值小于2好
#print(mse1)
#print(mse2)
#print(mse3)
#print(mse4)
#print(mse5)
print(mse6)
print(mse7)
print(mse8)
print(mse9)

In [ ]:
from __future__ import division
from sklearn.metrics import explained_variance_score, mean_absolute_error, mean_squared_error, r2_score
def calPerformance(y_true,y_pred):
    model_metrics_name=[explained_variance_score, mean_absolute_error, mean_squared_error, r2_score]  
    tmp_list=[]  
    for one in model_metrics_name:  
        tmp_score=one(y_true,y_pred)  
        tmp_list.append(tmp_score)  
    print ['explained_variance_score','mean_absolute_error','mean_squared_error','r2_score']
    print tmp_list
    return tmp_list
 
calPerformance(y_true,y_pred)